JSON schema file for YAML configuration schema validation
winsw/winsw pull request #656
Opened 2020-08-23 05:34 UTC by buddhikac96

Fixes https://github.com/winsw/winsw/issues/537

2020-08-25 05:41 UTC, oleg-nenashev commented on doc/yamlConfigFile.md
> +First you should convert YAML file into JSON and then you can
It is not needed if you use https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml . I would suggest documenting such use-case which is more friendly to users

2020-08-25 05:42 UTC, oleg-nenashev commented on doc/yamlConfigurationSchema.json
> +  "description": "This JSON schema validate the YAML configuaration file.",
Link the YAML config documentation page for more details?

2020-08-25 06:31 UTC, oleg-nenashev requested changes
I have tested it with https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml , and it works well. There is an issue with boolean properties which are registered as String with boolPattern in the schema. Would be great to actually make them boolean if possible, but it is a subject for a separate discussion with @buddhikac96 and @NextTurn . Might be fine as well

Requesting changes because of the typo

2020-08-25 06:31 UTC, oleg-nenashev commented on doc/yamlConfigurationSchema.json
> +  "description": "This JSON schema validate the YAML configuaration file.",
```suggestion
  "description": "This JSON schema validate the YAML configuration file.",
```

2020-08-27 08:53 UTC, oleg-nenashev approved these changes
Fine with me, thanks for addressing the comments.
We can definitely start from that and improve in follow-ups

2020-08-27 09:02 UTC, oleg-nenashev commented on doc/yamlConfigurationSchema.json
> +}
```suggestion
}

```

2020-08-27 09:09 UTC, buddhikac96 commented
> Fine with me, thanks for addressing the comments.
> We can definitely start from that and improve in follow-ups

Thanks. Are we willing to integrate YAML schema validation someday or we will keep it to use from VSCode?

2020-08-27 09:19 UTC, NextTurn commented on doc/yamlConfigFile.md
> +[Find the JSON schema in this link.](yamlConfigurationSchema.json)
After this link was removed the JSON file is not referenced anywhere.

2020-08-27 09:43 UTC, buddhikac96 commented on doc/yamlConfigFile.md
> +[Find the JSON schema in this link.](yamlConfigurationSchema.json)
So how should I reference the file? Just use the file name without a link?

2020-08-27 09:50 UTC, merged